/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChangesRouteImport } from './routes/_authenticated/changes'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedRenterRouteImport } from './routes/_authenticated/renter'
import { Route as AuthenticatedReviewerRouteImport } from './routes/_authenticated/reviewer'
import { Route as AuthenticatedPropertyAddressIdRouteImport } from './routes/_authenticated/property.$addressId'
import { Route as AuthenticatedRulesIdRouteImport } from './routes/_authenticated/rules.$id'
import { Route as AuthenticatedSourcesDocIdRouteImport } from './routes/_authenticated/sources.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangesRoute = AuthenticatedChangesRouteImport.update({
  id: '/_authenticated/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/_authenticated/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/_authenticated/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/_authenticated/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRenterRoute = AuthenticatedRenterRouteImport.update({
  id: '/_authenticated/renter',
  path: '/renter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewerRoute = AuthenticatedReviewerRouteImport.update({
  id: '/_authenticated/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertyAddressIdRoute =
  AuthenticatedPropertyAddressIdRouteImport.update({
    id: '/_authenticated/property/$addressId',
    path: '/property/$addressId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRulesIdRoute = AuthenticatedRulesIdRouteImport.update({
  id: '/_authenticated/rules/$id',
  path: '/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSourcesDocIdRoute =
  AuthenticatedSourcesDocIdRouteImport.update({
    id: '/_authenticated/sources/$docId',
    path: '/sources/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/changes': typeof AuthenticatedChangesRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/map': typeof AuthenticatedMapRoute
  '/renter': typeof AuthenticatedRenterRoute
  '/reviewer': typeof AuthenticatedReviewerRoute
  '/property/$addressId': typeof AuthenticatedPropertyAddressIdRoute
  '/rules/$id': typeof AuthenticatedRulesIdRoute
  '/sources/$docId': typeof AuthenticatedSourcesDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/changes': typeof AuthenticatedChangesRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/map': typeof AuthenticatedMapRoute
  '/renter': typeof AuthenticatedRenterRoute
  '/reviewer': typeof AuthenticatedReviewerRoute
  '/property/$addressId': typeof AuthenticatedPropertyAddressIdRoute
  '/rules/$id': typeof AuthenticatedRulesIdRoute
  '/sources/$docId': typeof AuthenticatedSourcesDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/changes': typeof AuthenticatedChangesRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/renter': typeof AuthenticatedRenterRoute
  '/_authenticated/reviewer': typeof AuthenticatedReviewerRoute
  '/_authenticated/property/$addressId': typeof AuthenticatedPropertyAddressIdRoute
  '/_authenticated/rules/$id': typeof AuthenticatedRulesIdRoute
  '/_authenticated/sources/$docId': typeof AuthenticatedSourcesDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/changes'
    | '/console'
    | '/manager'
    | '/map'
    | '/renter'
    | '/reviewer'
    | '/property/$addressId'
    | '/rules/$id'
    | '/sources/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/changes'
    | '/console'
    | '/manager'
    | '/map'
    | '/renter'
    | '/reviewer'
    | '/property/$addressId'
    | '/rules/$id'
    | '/sources/$docId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/changes'
    | '/_authenticated/console'
    | '/_authenticated/manager'
    | '/_authenticated/map'
    | '/_authenticated/renter'
    | '/_authenticated/reviewer'
    | '/_authenticated/property/$addressId'
    | '/_authenticated/rules/$id'
    | '/_authenticated/sources/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChangesRoute: typeof AuthenticatedChangesRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedRenterRoute: typeof AuthenticatedRenterRoute
  AuthenticatedReviewerRoute: typeof AuthenticatedReviewerRoute
  AuthenticatedPropertyAddressIdRoute: typeof AuthenticatedPropertyAddressIdRoute
  AuthenticatedRulesIdRoute: typeof AuthenticatedRulesIdRoute
  AuthenticatedSourcesDocIdRoute: typeof AuthenticatedSourcesDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/changes': {
      id: '/_authenticated/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AuthenticatedChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/renter': {
      id: '/_authenticated/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof AuthenticatedRenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviewer': {
      id: '/_authenticated/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof AuthenticatedReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/property/$addressId': {
      id: '/_authenticated/property/$addressId'
      path: '/property/$addressId'
      fullPath: '/property/$addressId'
      preLoaderRoute: typeof AuthenticatedPropertyAddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rules/$id': {
      id: '/_authenticated/rules/$id'
      path: '/rules/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof AuthenticatedRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources/$docId': {
      id: '/_authenticated/sources/$docId'
      path: '/sources/$docId'
      fullPath: '/sources/$docId'
      preLoaderRoute: typeof AuthenticatedSourcesDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChangesRoute: AuthenticatedChangesRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedRenterRoute: AuthenticatedRenterRoute,
  AuthenticatedReviewerRoute: AuthenticatedReviewerRoute,
  AuthenticatedPropertyAddressIdRoute: AuthenticatedPropertyAddressIdRoute,
  AuthenticatedRulesIdRoute: AuthenticatedRulesIdRoute,
  AuthenticatedSourcesDocIdRoute: AuthenticatedSourcesDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
