/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as MapRouteImport } from './routes/map'
import { Route as RenterRouteImport } from './routes/renter'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as PropertyAddressIdRouteImport } from './routes/property.$addressId'
import { Route as RulesIdRouteImport } from './routes/rules.$id'
import { Route as SourcesDocIdRouteImport } from './routes/sources.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterRoute = RenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyAddressIdRoute = PropertyAddressIdRouteImport.update({
  id: '/property/$addressId',
  path: '/property/$addressId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdRoute = RulesIdRouteImport.update({
  id: '/rules/$id',
  path: '/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesDocIdRoute = SourcesDocIdRouteImport.update({
  id: '/sources/$docId',
  path: '/sources/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/changes': typeof ChangesRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/renter': typeof RenterRoute
  '/reviewer': typeof ReviewerRoute
  '/property/$addressId': typeof PropertyAddressIdRoute
  '/rules/$id': typeof RulesIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/changes': typeof ChangesRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/renter': typeof RenterRoute
  '/reviewer': typeof ReviewerRoute
  '/property/$addressId': typeof PropertyAddressIdRoute
  '/rules/$id': typeof RulesIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/changes': typeof ChangesRoute
  '/manager': typeof ManagerRoute
  '/map': typeof MapRoute
  '/renter': typeof RenterRoute
  '/reviewer': typeof ReviewerRoute
  '/property/$addressId': typeof PropertyAddressIdRoute
  '/rules/$id': typeof RulesIdRoute
  '/sources/$docId': typeof SourcesDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/changes'
    | '/manager'
    | '/map'
    | '/renter'
    | '/reviewer'
    | '/property/$addressId'
    | '/rules/$id'
    | '/sources/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/changes'
    | '/manager'
    | '/map'
    | '/renter'
    | '/reviewer'
    | '/property/$addressId'
    | '/rules/$id'
    | '/sources/$docId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/changes'
    | '/manager'
    | '/map'
    | '/renter'
    | '/reviewer'
    | '/property/$addressId'
    | '/rules/$id'
    | '/sources/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChangesRoute: typeof ChangesRoute
  ManagerRoute: typeof ManagerRoute
  MapRoute: typeof MapRoute
  RenterRoute: typeof RenterRoute
  ReviewerRoute: typeof ReviewerRoute
  PropertyAddressIdRoute: typeof PropertyAddressIdRoute
  RulesIdRoute: typeof RulesIdRoute
  SourcesDocIdRoute: typeof SourcesDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter': {
      id: '/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof RenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$addressId': {
      id: '/property/$addressId'
      path: '/property/$addressId'
      fullPath: '/property/$addressId'
      preLoaderRoute: typeof PropertyAddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id': {
      id: '/rules/$id'
      path: '/rules/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof RulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$docId': {
      id: '/sources/$docId'
      path: '/sources/$docId'
      fullPath: '/sources/$docId'
      preLoaderRoute: typeof SourcesDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChangesRoute: ChangesRoute,
  ManagerRoute: ManagerRoute,
  MapRoute: MapRoute,
  RenterRoute: RenterRoute,
  ReviewerRoute: ReviewerRoute,
  PropertyAddressIdRoute: PropertyAddressIdRoute,
  RulesIdRoute: RulesIdRoute,
  SourcesDocIdRoute: SourcesDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
